import { Geist, Geist_Mono, Roboto, Ubuntu } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { Dashboard } from "@mui/icons-material";
import DashBoard from "./components/dashBoard";
import { Box } from "@mui/material";
import StoreProvider from "./storeProvider";

const RobotoSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const UbuntuSans = Ubuntu({
  variable: "--font-ubuntu-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${RobotoSans.variable} ${UbuntuSans.variable}`}>
        <Box style={{ display: "flex", height: "100vh", overflow: "hidden" }}>
          <DashBoard />
          <Box sx={{ flexGrow: 1 }}>
            <Header />
            {/* <StoreProvider store={store}>  */}
            {children}
            {/* </StoreProvider> */}
          </Box>
        </Box>
      </body>
    </html>
  );
}
